Repository Quansight-Labs/jupyter-a11y-mgmt, pull requests merged in 2021-11, with the labels that each got.

#38 add jupyter book as the documentation backbone for the project
  .github/workflows/docs.yml
  .gitignore
  docs/_config.yml
  docs/_toc.yml
  docs/readme.md
  docs/roadmap.md
  noxfile.py
Labels: status: PR opened ⛴, type: documentation :book:

#46 Create repo code of conduct
  CODE_OF_CONDUCT.md
Labels: status: changes requested 🚑, type: community :unicorn:

#47 :memo: Add contributing guidelines
  CONTRIBUTING.md
Labels: status: awaiting review 👀, type: community :unicorn:

#53 Update github action to only checks
  .github/workflows/docs.yml
Labels: type: bug :bug:, type: ci 👷🏽‍♀️
